In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
movies = pd.read_csv("/Users/priyangshubagchi/Downloads/archive (7)/tmdb_5000_movies.csv")
credits = pd.read_csv("/Users/priyangshubagchi/Downloads/archive (7)/tmdb_5000_credits.csv")
print(movies.shape)
movies.head()

(4803, 20)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [3]:
movies = movies[['title', 'overview', 'genres']]

movies.head()

,title,overview,genres
0,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam..."
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""..."
2,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam..."
3,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam..."
4,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam..."

In [4]:
movies.dropna(inplace=True)

movies.isnull().sum()

title       0
overview    0
genres      0
dtype: int64

In [5]:
movies['tags'] = movies['overview']

movies[['title', 'tags']].head()

,title,tags
0,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,Spectre,A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,Following the death of District Attorney Harve...
4,John Carter,"John Carter is a war-weary, former military ca..."

In [6]:
tfidf = TfidfVectorizer(
    stop_words='english',
    max_features=5000
)

vectors = tfidf.fit_transform(movies['tags'])

In [7]:
similarity = cosine_similarity(vectors)

print(similarity.shape)

(4800, 4800)

In [8]:
def recommend(movie_name):

    movie_name = movie_name.lower()

    matches = movies[
        movies['title'].str.lower() == movie_name
    ]

    if matches.empty:
        print("Movie not found!")
        return

    index = matches.index[0]

    distances = list(
        enumerate(similarity[index])
    )

    distances = sorted(
        distances,
        key=lambda x: x[1],
        reverse=True
    )

    print("\nTop 5 Recommendations:\n")

    for movie in distances[1:6]:
        print(
            movies.iloc[movie[0]].title
        )

In [9]:
recommend("Avatar")

Top 5 Recommendations:

Apollo 18
The American
Beowulf
Tears of the Sun
The Adventures of Pluto Nash

In [10]:
recommend("The Dark Knight")

Top 5 Recommendations:

The Dark Knight Rises
Batman Forever
Batman Returns
Batman: The Dark Knight Returns, Part 2
Batman Begins

In [11]:
movie = input("Enter Movie Name: ")

recommend(movie)

Enter Movie Name:  avatar

Top 5 Recommendations:

Apollo 18
The American
Beowulf
Tears of the Sun
The Adventures of Pluto Nash

In [12]:
top_movies = movies.sort_values(
    by='title'
)

print(top_movies[['title']].head(10))

                           title
4257                     #Horror
3339        (500) Days of Summer
3556         10 Cloverfield Lane
2903       10 Days in a Madhouse
2739  10 Things I Hate About You
393               102 Dalmatians
3293                 10th & Wolf
3504                       11:14
4602                12 Angry Men
2207                   12 Rounds

In [13]:
print("""
MOVIE RECOMMENDATION SYSTEM REPORT

1. TMDb movie dataset was used.
2. Missing values were removed.
3. TF-IDF vectorization converted text into numerical features.
4. Cosine similarity measured similarity between movies.
5. Content-based filtering was implemented.
6. System successfully recommends top 5 similar movies.
7. Recommendation quality depends on movie overview descriptions.
""")

MOVIE RECOMMENDATION SYSTEM REPORT

1. TMDb movie dataset was used.
2. Missing values were removed.
3. TF-IDF vectorization converted text into numerical features.
4. Cosine similarity measured similarity between movies.
5. Content-based filtering was implemented.
6. System successfully recommends top 5 similar movies.
7. Recommendation quality depends on movie overview descriptions.